[project]
name = "turtlewatch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "influxdb3-python>=0.16.0",
]
[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
bridge = { workspace = true }
msg_gen = { workspace = true }

[tool.pyright]
typeCheckingMode = "strict"
reportUnknownMemberType = false
reportUnusedCallResult = false
reportMissingTypeStubs = false
